// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.5.2
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace ColorsGame.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.5.2")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class N2NCreateGameRoundFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CreateGameRoundN2N.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "N2N Create game round", "1.Administrator initial TableCount, DurationTime, IntervalTime\r\n2.Display Sample " +
                    "game tables\r\n3.Admin config and save game configurations and Display game tables" +
                    "", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            this.FeatureBackground();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
testRunner.Given("Create and initialize CreateGameRoundPage");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "TableID",
                        "GameDuration",
                        "Interval"});
            table1.AddRow(new string[] {
                        "1",
                        "20",
                        "5"});
            table1.AddRow(new string[] {
                        "2",
                        "20",
                        "10"});
            table1.AddRow(new string[] {
                        "3",
                        "20",
                        "7"});
#line 8
testRunner.And("the table configuration set \'config1\' has the following data", ((string)(null)), table1);
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Initialize game configuration complete , sampel tables has created")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "N2N Create game round")]
        public virtual void InitializeGameConfigurationCompleteSampelTablesHasCreated()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Initialize game configuration complete , sampel tables has created", ((string[])(null)));
#line 14
this.ScenarioSetup(scenarioInfo);
#line 15
testRunner.Given("Config TableCount: 5, DurationTime: 120 minute, IntervalTime: 5 minute");
#line 16
testRunner.When("I press Save");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "TableID",
                        "GameDuration",
                        "Interval"});
            table2.AddRow(new string[] {
                        "1",
                        "120",
                        "5"});
            table2.AddRow(new string[] {
                        "2",
                        "120",
                        "5"});
            table2.AddRow(new string[] {
                        "3",
                        "120",
                        "5"});
            table2.AddRow(new string[] {
                        "4",
                        "120",
                        "5"});
            table2.AddRow(new string[] {
                        "5",
                        "120",
                        "5"});
#line 17
testRunner.Then("sample tables has created", ((string)(null)), table2);
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Save game configuration TableCount: 0, skip generate sample tables")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "N2N Create game round")]
        public virtual void SaveGameConfigurationTableCount0SkipGenerateSampleTables()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Save game configuration TableCount: 0, skip generate sample tables", ((string[])(null)));
#line 25
this.ScenarioSetup(scenarioInfo);
#line 26
testRunner.Given("Config TableCount: 0, DurationTime: 120 minute, IntervalTime: 5 minute");
#line 27
testRunner.When("I press Save");
#line 28
testRunner.Then("display sample tables has skip");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Save game configuration using TableCount is minus value, skip generate sample tab" +
            "les")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "N2N Create game round")]
        public virtual void SaveGameConfigurationUsingTableCountIsMinusValueSkipGenerateSampleTables()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Save game configuration using TableCount is minus value, skip generate sample tab" +
                    "les", ((string[])(null)));
#line 30
this.ScenarioSetup(scenarioInfo);
#line 31
testRunner.Given("Config TableCount: -1, DurationTime: 120 minute, IntervalTime: 5 minute");
#line 32
testRunner.When("I press Save");
#line 33
testRunner.Then("display sample tables has skip");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Save game configuration using DurationTime is minus value, skip generate sample t" +
            "ables")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "N2N Create game round")]
        public virtual void SaveGameConfigurationUsingDurationTimeIsMinusValueSkipGenerateSampleTables()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Save game configuration using DurationTime is minus value, skip generate sample t" +
                    "ables", ((string[])(null)));
#line 35
this.ScenarioSetup(scenarioInfo);
#line 36
testRunner.Given("Config TableCount: 5, DurationTime: -1 minute, IntervalTime: 5 minute");
#line 37
testRunner.When("I press Save");
#line 38
testRunner.Then("display sample tables has skip");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Save game configuration using IntervalTime is minus value, skip generate sample t" +
            "ables")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "N2N Create game round")]
        public virtual void SaveGameConfigurationUsingIntervalTimeIsMinusValueSkipGenerateSampleTables()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Save game configuration using IntervalTime is minus value, skip generate sample t" +
                    "ables", ((string[])(null)));
#line 40
this.ScenarioSetup(scenarioInfo);
#line 41
testRunner.Given("Config TableCount: 5, DurationTime: 120 minute, IntervalTime: -1 minute");
#line 42
testRunner.When("I press Save");
#line 43
testRunner.Then("display sample tables has skip");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Save game configuration using TableCount,DurationTime,IntervalTime are minus valu" +
            "e, skip generate sample tables")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "N2N Create game round")]
        public virtual void SaveGameConfigurationUsingTableCountDurationTimeIntervalTimeAreMinusValueSkipGenerateSampleTables()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Save game configuration using TableCount,DurationTime,IntervalTime are minus valu" +
                    "e, skip generate sample tables", ((string[])(null)));
#line 45
this.ScenarioSetup(scenarioInfo);
#line 46
testRunner.Given("Config TableCount: -1, DurationTime: -1 minute, IntervalTime: -1 minute");
#line 47
testRunner.When("I press Save");
#line 48
testRunner.Then("display sample tables has skip");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Generate table from configuration name: \'config1\' accept")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "N2N Create game round")]
        public virtual void GenerateTableFromConfigurationNameConfig1Accept()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Generate table from configuration name: \'config1\' accept", ((string[])(null)));
#line 50
this.ScenarioSetup(scenarioInfo);
#line 51
testRunner.When("Generate from configuration name \'config1\'");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "TableID",
                        "RoundID",
                        "StartTime",
                        "EndTime"});
            table3.AddRow(new string[] {
                        "1",
                        "1",
                        "10:00",
                        "10:20"});
            table3.AddRow(new string[] {
                        "2",
                        "2",
                        "10:05",
                        "10:25"});
            table3.AddRow(new string[] {
                        "3",
                        "3",
                        "10:15",
                        "10:35"});
#line 52
testRunner.Then("The active game table are", ((string)(null)), table3);
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
