// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.5.2
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace TheS.Casinova.PlayerProfile.WebExecutors.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.5.2")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ChangeEmailFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ChangeEmailFeature.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ChangeEmail", "In order to change email\r\nAs a system\r\nI want to change new email", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ระบบไดรบขอมลอเมลใหมจากผเลนระบบทำการตรวจสอบขอมลและUpdateขอมลตอไป(string userName, string oldEmail, string newEmail)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ระบบได้รับข้อมูลอีเมลใหม่จากผู้เล่น ระบบทำการตรวจสอบข้อมูล และ update ข้อมูลต่อไป" +
                    "", new string[] {
                        "record_mock"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
testRunner.Given("The ChangeEmailExecutor has been created and initializedr");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "UserName",
                        "Email"});
            table1.AddRow(new string[] {
                        "Nit",
                        "nayit_nit@hotmail.com"});
#line 9
testRunner.And("Server has email information of Nit :", ((string)(null)), table1);
#line 13
testRunner.And(string.Format("Sent UserName \'{0}\' OldEmail \'{1}\' NewEmail \'{2}\'", userName, oldEmail, newEmail));
#line 14
testRunner.When("Call ChangeEmailExecutor");
#line 15
testRunner.Then("The system can update new email");
#line 16
testRunner.Then("The system can\'t update new email");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบได้รับข้อมูลอีเมลใหม่จากผู้เล่น ระบบทำการตรวจสอบข้อมูล และ update ข้อมูลต่อไป" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ChangeEmail")]
        public virtual void ระบบไดรบขอมลอเมลใหมจากผเลนระบบทำการตรวจสอบขอมลและUpdateขอมลตอไป_Variant0()
        {
            this.ระบบไดรบขอมลอเมลใหมจากผเลนระบบทำการตรวจสอบขอมลและUpdateขอมลตอไป("Nit", "nayit_nit@hotmail.com", "nittaya@perfenterprise.com");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบได้รับข้อมูลอีเมลใหม่จากผู้เล่น ระบบทำการตรวจสอบข้อมูล และ update ข้อมูลต่อไป" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ChangeEmail")]
        public virtual void ระบบไดรบขอมลอเมลใหมจากผเลนระบบทำการตรวจสอบขอมลและUpdateขอมลตอไป_Variant1()
        {
            this.ระบบไดรบขอมลอเมลใหมจากผเลนระบบทำการตรวจสอบขอมลและUpdateขอมลตอไป("Nit", "nayit_n_@hotmail.com", "nittaya@perfenterprise.com");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบได้รับข้อมูลอีเมลใหม่จากผู้เล่น ระบบทำการตรวจสอบข้อมูล และ update ข้อมูลต่อไป" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ChangeEmail")]
        public virtual void ระบบไดรบขอมลอเมลใหมจากผเลนระบบทำการตรวจสอบขอมลและUpdateขอมลตอไป_Variant2()
        {
            this.ระบบไดรบขอมลอเมลใหมจากผเลนระบบทำการตรวจสอบขอมลและUpdateขอมลตอไป("Nit", "nayit_nit@hotmail.com", "nittaya.com");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบได้รับข้อมูลอีเมลใหม่จากผู้เล่น ระบบทำการตรวจสอบข้อมูล และ update ข้อมูลต่อไป" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ChangeEmail")]
        public virtual void ระบบไดรบขอมลอเมลใหมจากผเลนระบบทำการตรวจสอบขอมลและUpdateขอมลตอไป_Variant3()
        {
            this.ระบบไดรบขอมลอเมลใหมจากผเลนระบบทำการตรวจสอบขอมลและUpdateขอมลตอไป("Nit", "nayit1311", "nittaya@perfenterprise.com");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบได้รับข้อมูลอีเมลใหม่จากผู้เล่น ระบบทำการตรวจสอบข้อมูล และ update ข้อมูลต่อไป" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ChangeEmail")]
        public virtual void ระบบไดรบขอมลอเมลใหมจากผเลนระบบทำการตรวจสอบขอมลและUpdateขอมลตอไป_Variant4()
        {
            this.ระบบไดรบขอมลอเมลใหมจากผเลนระบบทำการตรวจสอบขอมลและUpdateขอมลตอไป("", "nayit_nit@hotmail.com", "nittaya@perfenterprise.com");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบได้รับข้อมูลอีเมลใหม่จากผู้เล่น ระบบทำการตรวจสอบข้อมูล และ update ข้อมูลต่อไป" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ChangeEmail")]
        public virtual void ระบบไดรบขอมลอเมลใหมจากผเลนระบบทำการตรวจสอบขอมลและUpdateขอมลตอไป_Variant5()
        {
            this.ระบบไดรบขอมลอเมลใหมจากผเลนระบบทำการตรวจสอบขอมลและUpdateขอมลตอไป("Nit", "", "nittaya@perfenterprise.com");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบได้รับข้อมูลอีเมลใหม่จากผู้เล่น ระบบทำการตรวจสอบข้อมูล และ update ข้อมูลต่อไป" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ChangeEmail")]
        public virtual void ระบบไดรบขอมลอเมลใหมจากผเลนระบบทำการตรวจสอบขอมลและUpdateขอมลตอไป_Variant6()
        {
            this.ระบบไดรบขอมลอเมลใหมจากผเลนระบบทำการตรวจสอบขอมลและUpdateขอมลตอไป("Nit", "nayit_nit@hotmail.com", "");
        }
    }
}
#endregion
