// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.5.2
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace TheS.Casinova.DevilSix.WebExecutors.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.5.2")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ListGamePlayAutoBetInfoFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ListGamePlayAutoBetInfoFeature.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ListGamePlayAutoBetInfo", "In order to ให้ผู้เล่นทราบจำนวนเงินทั้งหมดที่ได้ลงเดิมพันแบบ auto bet ยังไม่เสร็จ" +
                    "ที่โต๊ะเกมนั้น ๆ\r\nAs a User\r\nI want ดึงข้อมูลการลงเดิมพันแบบ auto bet", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[ListGamePlayAutoBet]ระบบได้รับข้อมูล userName ถูกต้อง และใน server มีข้อมูลการลง" +
            "เดิมพันแบบอัตโนมัติไว้ ระบบสามารถดึงข้อมูลการลงเดิมพันแบบอัตโนมัติได้")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ListGamePlayAutoBetInfo")]
        public virtual void ListGamePlayAutoBetระบบไดรบขอมลUserNameถกตองและในServerมขอมลการลงเดมพนแบบอตโนมตไวระบบสามารถดงขอมลการลงเดมพนแบบอตโนมตได()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[ListGamePlayAutoBet]ระบบได้รับข้อมูล userName ถูกต้อง และใน server มีข้อมูลการลง" +
                    "เดิมพันแบบอัตโนมัติไว้ ระบบสามารถดึงข้อมูลการลงเดิมพันแบบอัตโนมัติได้", new string[] {
                        "record_mock"});
#line 9
this.ScenarioSetup(scenarioInfo);
#line 10
testRunner.Given("The ListGamePlayAutoBetInfoExecutor has been created and initialized");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "UserName",
                        "RoundID",
                        "Amount",
                        "Interval",
                        "MoneyRefund",
                        "BetTrackingID",
                        "ThruDateTime"});
            table1.AddRow(new string[] {
                        "Nit",
                        "1",
                        "200",
                        "5",
                        "0",
                        "083CE9EC-7459-4A5A-9771-DD3E04D192D6",
                        "00:00"});
            table1.AddRow(new string[] {
                        "Nit",
                        "2",
                        "300",
                        "10",
                        "100",
                        "A92343C8-2484-4928-A95E-9BD3BAE17FD9",
                        "12:00"});
            table1.AddRow(new string[] {
                        "OhAe",
                        "1",
                        "200",
                        "2",
                        "0",
                        "DBAF58AD-EDB0-4BB8-AC8B-C783D23E73FC",
                        "00:00"});
#line 11
testRunner.And("Server has game play auto bet information as:", ((string)(null)), table1);
#line 16
testRunner.And("Sent UserName \'Nit\'");
#line 17
testRunner.When("Call ListGamePlayAutoBetInfoExecutor()");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "UserName",
                        "RoundID",
                        "Amount",
                        "Interval",
                        "MoneyRefund",
                        "BetTrackingID",
                        "ThruDateTime"});
            table2.AddRow(new string[] {
                        "Nit",
                        "1",
                        "200",
                        "5",
                        "0",
                        "083CE9EC-7459-4A5A-9771-DD3E04D192D6",
                        "00:00"});
            table2.AddRow(new string[] {
                        "Nit",
                        "2",
                        "300",
                        "10",
                        "100",
                        "A92343C8-2484-4928-A95E-9BD3BAE17FD9",
                        "12:00"});
#line 18
testRunner.Then("The game play auto bet information should be as :", ((string)(null)), table2);
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[ListGamePlayAutoBet]ระบบได้รับข้อมูล userName ถูกต้อง แต่ใน server ไม่มีข้อมูลกา" +
            "รลงเดิมพันแบบอัตโนมัติไว้ ได้ข้อมูลการลงเดิมพันแบบอัตโนมัติเป็น null")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ListGamePlayAutoBetInfo")]
        public virtual void ListGamePlayAutoBetระบบไดรบขอมลUserNameถกตองแตในServerไมมขอมลการลงเดมพนแบบอตโนมตไวไดขอมลการลงเดมพนแบบอตโนมตเปนNull()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[ListGamePlayAutoBet]ระบบได้รับข้อมูล userName ถูกต้อง แต่ใน server ไม่มีข้อมูลกา" +
                    "รลงเดิมพันแบบอัตโนมัติไว้ ได้ข้อมูลการลงเดิมพันแบบอัตโนมัติเป็น null", new string[] {
                        "record_mock"});
#line 24
this.ScenarioSetup(scenarioInfo);
#line 25
testRunner.Given("The ListGamePlayAutoBetInfoExecutor has been created and initialized");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "UserName",
                        "RoundID",
                        "Amount",
                        "Interval",
                        "MoneyRefund",
                        "BetTrackingID",
                        "ThruDateTime"});
            table3.AddRow(new string[] {
                        "Nit",
                        "1",
                        "200",
                        "5",
                        "0",
                        "083CE9EC-7459-4A5A-9771-DD3E04D192D6",
                        "00:00"});
            table3.AddRow(new string[] {
                        "Nit",
                        "2",
                        "300",
                        "10",
                        "100",
                        "A92343C8-2484-4928-A95E-9BD3BAE17FD9",
                        "12:00"});
            table3.AddRow(new string[] {
                        "OhAe",
                        "1",
                        "200",
                        "2",
                        "0",
                        "DBAF58AD-EDB0-4BB8-AC8B-C783D23E73FC",
                        "00:00"});
#line 26
testRunner.And("Server has game play auto bet information as:", ((string)(null)), table3);
#line 31
testRunner.And("Sent UserName \'Gogo\'");
#line 32
testRunner.When("Call ListGamePlayAutoBetInfoExecutor()");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "UserName",
                        "RoundID",
                        "Amount",
                        "Interval",
                        "MoneyRefund",
                        "BetTrackingID",
                        "ThruDateTime"});
#line 33
testRunner.Then("The game play auto bet information should be as :", ((string)(null)), table4);
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[ListGamePlayAutoBet]ระบบไม่ได้รับข้อมูล userName ระบบไม่สามารถลิสต์ข้อมูลการลงเด" +
            "ิมพันแบบอัตโนมัติได้")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ListGamePlayAutoBetInfo")]
        public virtual void ListGamePlayAutoBetระบบไมไดรบขอมลUserNameระบบไมสามารถลสตขอมลการลงเดมพนแบบอตโนมตได()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[ListGamePlayAutoBet]ระบบไม่ได้รับข้อมูล userName ระบบไม่สามารถลิสต์ข้อมูลการลงเด" +
                    "ิมพันแบบอัตโนมัติได้", new string[] {
                        "record_mock"});
#line 37
this.ScenarioSetup(scenarioInfo);
#line 38
testRunner.Given("The ListGamePlayAutoBetInfoExecutor has been created and initialized");
#line 39
testRunner.And("Sent UserName \'\' for validation");
#line 40
testRunner.When("Call ListGamePlayAutoBetInfoExecutor() for validate input");
#line 41
testRunner.Then("The game play auto bet information should be throw exception");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
