// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.5.2
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace TheS.Casinova.DevilSix.WebExecutors.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.5.2")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class StartAutoBetFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "StartAutoBetFeature.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "StartAutoBet", "In order to ให้ผู้เล่นลงพนันได้ต่อเนื่อง และไม่ต้องเฝ้าอยู่ที่หน้าเกมส์\r\nAs a Use" +
                    "r\r\nI want ให้ Server หักเงินลงพนันให้ผู้เล่นโดยอัตโนมัติ", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[StartAutoBet]ระบบได้รับข้อมูลการลงเดิมพันแบบอัตโนมัติ ระบบทำการตรวจสอบข้อมูล ข้อ" +
            "มูลถูกต้อง ระบบทำการ generate trackingID")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "StartAutoBet")]
        public virtual void StartAutoBetระบบไดรบขอมลการลงเดมพนแบบอตโนมตระบบทำการตรวจสอบขอมลขอมลถกตองระบบทำการGenerateTrackingID()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[StartAutoBet]ระบบได้รับข้อมูลการลงเดิมพันแบบอัตโนมัติ ระบบทำการตรวจสอบข้อมูล ข้อ" +
                    "มูลถูกต้อง ระบบทำการ generate trackingID", new string[] {
                        "record_mock"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
testRunner.Given("The StartAutoBetExecutor has been created and initialized");
#line 9
testRunner.And("Sent StartAutoBetInformation UserName \'Bebo\' RoundID \'3\' Amount \'50\' Interval \'2\'" +
                    " TotalAmount \'100\'");
#line 10
testRunner.And("The system generated TrackingID for start auto bet:\'955D6ACDE4E04D1C90ACF3715BB26" +
                    "85A\'");
#line 11
testRunner.When("Call StartAutoBetExecutor()");
#line 12
testRunner.Then("TrackingID for StartAutoBet should be :\'955D6ACDE4E04D1C90ACF3715BB2685A\'");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void StartAutoBetระบบไดรบขอมลการลงเดมพนแบบอตโนมตระบบทำการตรวจสอบขอมลขอมลไมถกตองระบบไมทำการGenerateTrackingID(string userName, string roundID, string amount, string interval, string totalAmount)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[StartAutoBet]ระบบได้รับข้อมูลการลงเดิมพันแบบอัตโนมัติ ระบบทำการตรวจสอบข้อมูล ข้อ" +
                    "มูลไม่ถูกต้อง ระบบไม่ทำการ generate trackingID", new string[] {
                        "record_mock"});
#line 15
this.ScenarioSetup(scenarioInfo);
#line 16
testRunner.Given("The StartAutoBetExecutor has been created and initialized");
#line 17
testRunner.And(string.Format("Sent StartAutoBetInformation UserName \'{0}\' RoundID \'{1}\' Amount \'{2}\' Interval \'" +
                        "{3}\' TotalAmount \'{4}\'", userName, roundID, amount, interval, totalAmount));
#line 18
testRunner.When("Call StartAutoBetExecutor() for validation");
#line 19
testRunner.Then("StartAutoBet get null and skip checking trackingID");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[StartAutoBet]ระบบได้รับข้อมูลการลงเดิมพันแบบอัตโนมัติ ระบบทำการตรวจสอบข้อมูล ข้อ" +
            "มูลไม่ถูกต้อง ระบบไม่ทำการ generate trackingID")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "StartAutoBet")]
        public virtual void StartAutoBetระบบไดรบขอมลการลงเดมพนแบบอตโนมตระบบทำการตรวจสอบขอมลขอมลไมถกตองระบบไมทำการGenerateTrackingID_Variant0()
        {
            this.StartAutoBetระบบไดรบขอมลการลงเดมพนแบบอตโนมตระบบทำการตรวจสอบขอมลขอมลไมถกตองระบบไมทำการGenerateTrackingID("", "1", "1", "10", "20");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[StartAutoBet]ระบบได้รับข้อมูลการลงเดิมพันแบบอัตโนมัติ ระบบทำการตรวจสอบข้อมูล ข้อ" +
            "มูลไม่ถูกต้อง ระบบไม่ทำการ generate trackingID")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "StartAutoBet")]
        public virtual void StartAutoBetระบบไดรบขอมลการลงเดมพนแบบอตโนมตระบบทำการตรวจสอบขอมลขอมลไมถกตองระบบไมทำการGenerateTrackingID_Variant1()
        {
            this.StartAutoBetระบบไดรบขอมลการลงเดมพนแบบอตโนมตระบบทำการตรวจสอบขอมลขอมลไมถกตองระบบไมทำการGenerateTrackingID("Nit", "-1", "1", "1", "200");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[StartAutoBet]ระบบได้รับข้อมูลการลงเดิมพันแบบอัตโนมัติ ระบบทำการตรวจสอบข้อมูล ข้อ" +
            "มูลไม่ถูกต้อง ระบบไม่ทำการ generate trackingID")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "StartAutoBet")]
        public virtual void StartAutoBetระบบไดรบขอมลการลงเดมพนแบบอตโนมตระบบทำการตรวจสอบขอมลขอมลไมถกตองระบบไมทำการGenerateTrackingID_Variant2()
        {
            this.StartAutoBetระบบไดรบขอมลการลงเดมพนแบบอตโนมตระบบทำการตรวจสอบขอมลขอมลไมถกตองระบบไมทำการGenerateTrackingID("Nit", "6", "1", "1", "22");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[StartAutoBet]ระบบได้รับข้อมูลการลงเดิมพันแบบอัตโนมัติ ระบบทำการตรวจสอบข้อมูล ข้อ" +
            "มูลไม่ถูกต้อง ระบบไม่ทำการ generate trackingID")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "StartAutoBet")]
        public virtual void StartAutoBetระบบไดรบขอมลการลงเดมพนแบบอตโนมตระบบทำการตรวจสอบขอมลขอมลไมถกตองระบบไมทำการGenerateTrackingID_Variant3()
        {
            this.StartAutoBetระบบไดรบขอมลการลงเดมพนแบบอตโนมตระบบทำการตรวจสอบขอมลขอมลไมถกตองระบบไมทำการGenerateTrackingID("Nit", "1", "10", "1", "20");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[StartAutoBet]ระบบได้รับข้อมูลการลงเดิมพันแบบอัตโนมัติ ระบบทำการตรวจสอบข้อมูล ข้อ" +
            "มูลไม่ถูกต้อง ระบบไม่ทำการ generate trackingID")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "StartAutoBet")]
        public virtual void StartAutoBetระบบไดรบขอมลการลงเดมพนแบบอตโนมตระบบทำการตรวจสอบขอมลขอมลไมถกตองระบบไมทำการGenerateTrackingID_Variant4()
        {
            this.StartAutoBetระบบไดรบขอมลการลงเดมพนแบบอตโนมตระบบทำการตรวจสอบขอมลขอมลไมถกตองระบบไมทำการGenerateTrackingID("Nit", "1", "1", "0", "20");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[StartAutoBet]ระบบได้รับข้อมูลการลงเดิมพันแบบอัตโนมัติ ระบบทำการตรวจสอบข้อมูล ข้อ" +
            "มูลไม่ถูกต้อง ระบบไม่ทำการ generate trackingID")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "StartAutoBet")]
        public virtual void StartAutoBetระบบไดรบขอมลการลงเดมพนแบบอตโนมตระบบทำการตรวจสอบขอมลขอมลไมถกตองระบบไมทำการGenerateTrackingID_Variant5()
        {
            this.StartAutoBetระบบไดรบขอมลการลงเดมพนแบบอตโนมตระบบทำการตรวจสอบขอมลขอมลไมถกตองระบบไมทำการGenerateTrackingID("Nit", "4", "500", "5", "200");
        }
    }
}
#endregion
