// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.5.2
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace TheS.Casinova.PlayerAccount.WebExecutors.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.5.2")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class EditplayerAccountFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "EditPlayerAccountFeature.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "EditplayerAccount", "In order to edit player account\r\nAs a system\r\nI want to edit player account infor" +
                    "mation", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void EditPlayerAccountระบบไดรบขอมลPlayerAccountทมการแกไขระบบทำการตรวจสอบขอมลมการกรอกขอมลไมถกตองระบบไมสามารถสงขอมลไปทำการแกไขบญชผใชได(string userName, string accountType, string cardType, string accountNo, string cVV, string expireDate)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[EditPlayerAccount]ระบบได้รับข้อมูล PlayerAccount ที่มีการแก้ไข ระบบทำการตรวจสอบข" +
                    "้อมูล มีการกรอกข้อมูลไม่ถูกต้อง ระบบไม่สามารถส่งข้อมูลไปทำการแก้ไขบัญชีผู้ใช้ได้" +
                    "", new string[] {
                        "record_mock"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
testRunner.Given("The EditPlayerAccountExecutor has been created and initialized");
#line 9
testRunner.And(string.Format("Sent UserName \'{0}\' AccountType\'{1}\' CardType\'{2}\' AccountNo\'{3}\' CVV\'{4}\' Expire" +
                        "Date\'{5}\'", userName, accountType, cardType, accountNo, cVV, expireDate));
#line 10
testRunner.When("Call EditPlayerAccountExecutor() for validate input");
#line 11
testRunner.Then("Skip credit card validation to edit player account");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[EditPlayerAccount]ระบบได้รับข้อมูล PlayerAccount ที่มีการแก้ไข ระบบทำการตรวจสอบข" +
            "้อมูล มีการกรอกข้อมูลไม่ถูกต้อง ระบบไม่สามารถส่งข้อมูลไปทำการแก้ไขบัญชีผู้ใช้ได้" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EditplayerAccount")]
        public virtual void EditPlayerAccountระบบไดรบขอมลPlayerAccountทมการแกไขระบบทำการตรวจสอบขอมลมการกรอกขอมลไมถกตองระบบไมสามารถสงขอมลไปทำการแกไขบญชผใชได_Variant0()
        {
            this.EditPlayerAccountระบบไดรบขอมลPlayerAccountทมการแกไขระบบทำการตรวจสอบขอมลมการกรอกขอมลไมถกตองระบบไมสามารถสงขอมลไปทำการแกไขบญชผใชได("", "Primary", "Visa", "5585067151394716", "3223", "12/31/2011");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[EditPlayerAccount]ระบบได้รับข้อมูล PlayerAccount ที่มีการแก้ไข ระบบทำการตรวจสอบข" +
            "้อมูล มีการกรอกข้อมูลไม่ถูกต้อง ระบบไม่สามารถส่งข้อมูลไปทำการแก้ไขบัญชีผู้ใช้ได้" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EditplayerAccount")]
        public virtual void EditPlayerAccountระบบไดรบขอมลPlayerAccountทมการแกไขระบบทำการตรวจสอบขอมลมการกรอกขอมลไมถกตองระบบไมสามารถสงขอมลไปทำการแกไขบญชผใชได_Variant1()
        {
            this.EditPlayerAccountระบบไดรบขอมลPlayerAccountทมการแกไขระบบทำการตรวจสอบขอมลมการกรอกขอมลไมถกตองระบบไมสามารถสงขอมลไปทำการแกไขบญชผใชได("Nit", "", "", "5585067151394716", "3223", "12/31/2011");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[EditPlayerAccount]ระบบได้รับข้อมูล PlayerAccount ที่มีการแก้ไข ระบบทำการตรวจสอบข" +
            "้อมูล มีการกรอกข้อมูลไม่ถูกต้อง ระบบไม่สามารถส่งข้อมูลไปทำการแก้ไขบัญชีผู้ใช้ได้" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EditplayerAccount")]
        public virtual void EditPlayerAccountระบบไดรบขอมลPlayerAccountทมการแกไขระบบทำการตรวจสอบขอมลมการกรอกขอมลไมถกตองระบบไมสามารถสงขอมลไปทำการแกไขบญชผใชได_Variant2()
        {
            this.EditPlayerAccountระบบไดรบขอมลPlayerAccountทมการแกไขระบบทำการตรวจสอบขอมลมการกรอกขอมลไมถกตองระบบไมสามารถสงขอมลไปทำการแกไขบญชผใชได("Nit", "Primary", "Visa", "001221454454", "3223", "12/31/2011");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[EditPlayerAccount]ระบบได้รับข้อมูล PlayerAccount ที่มีการแก้ไข ระบบทำการตรวจสอบข" +
            "้อมูล มีการกรอกข้อมูลไม่ถูกต้อง ระบบไม่สามารถส่งข้อมูลไปทำการแก้ไขบัญชีผู้ใช้ได้" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EditplayerAccount")]
        public virtual void EditPlayerAccountระบบไดรบขอมลPlayerAccountทมการแกไขระบบทำการตรวจสอบขอมลมการกรอกขอมลไมถกตองระบบไมสามารถสงขอมลไปทำการแกไขบญชผใชได_Variant3()
        {
            this.EditPlayerAccountระบบไดรบขอมลPlayerAccountทมการแกไขระบบทำการตรวจสอบขอมลมการกรอกขอมลไมถกตองระบบไมสามารถสงขอมลไปทำการแกไขบญชผใชได("Nit", "Primary", "Visa", "", "3223", "12/31/2011");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[EditPlayerAccount]ระบบได้รับข้อมูล PlayerAccount ที่มีการแก้ไข ระบบทำการตรวจสอบข" +
            "้อมูล มีการกรอกข้อมูลไม่ถูกต้อง ระบบไม่สามารถส่งข้อมูลไปทำการแก้ไขบัญชีผู้ใช้ได้" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EditplayerAccount")]
        public virtual void EditPlayerAccountระบบไดรบขอมลPlayerAccountทมการแกไขระบบทำการตรวจสอบขอมลมการกรอกขอมลไมถกตองระบบไมสามารถสงขอมลไปทำการแกไขบญชผใชได_Variant4()
        {
            this.EditPlayerAccountระบบไดรบขอมลPlayerAccountทมการแกไขระบบทำการตรวจสอบขอมลมการกรอกขอมลไมถกตองระบบไมสามารถสงขอมลไปทำการแกไขบญชผใชได("Nit", "Primary", "Visa", "55850671513947164", "3223", "12/31/2011");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[EditPlayerAccount]ระบบได้รับข้อมูล PlayerAccount ที่มีการแก้ไข ระบบทำการตรวจสอบข" +
            "้อมูล มีการกรอกข้อมูลไม่ถูกต้อง ระบบไม่สามารถส่งข้อมูลไปทำการแก้ไขบัญชีผู้ใช้ได้" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EditplayerAccount")]
        public virtual void EditPlayerAccountระบบไดรบขอมลPlayerAccountทมการแกไขระบบทำการตรวจสอบขอมลมการกรอกขอมลไมถกตองระบบไมสามารถสงขอมลไปทำการแกไขบญชผใชได_Variant5()
        {
            this.EditPlayerAccountระบบไดรบขอมลPlayerAccountทมการแกไขระบบทำการตรวจสอบขอมลมการกรอกขอมลไมถกตองระบบไมสามารถสงขอมลไปทำการแกไขบญชผใชได("Nit", "Primary", "Visa", "5585067151394716", "3", "12/31/2011");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[EditPlayerAccount]ระบบได้รับข้อมูล PlayerAccount ที่มีการแก้ไข ระบบทำการตรวจสอบข" +
            "้อมูล มีการกรอกข้อมูลไม่ถูกต้อง ระบบไม่สามารถส่งข้อมูลไปทำการแก้ไขบัญชีผู้ใช้ได้" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EditplayerAccount")]
        public virtual void EditPlayerAccountระบบไดรบขอมลPlayerAccountทมการแกไขระบบทำการตรวจสอบขอมลมการกรอกขอมลไมถกตองระบบไมสามารถสงขอมลไปทำการแกไขบญชผใชได_Variant6()
        {
            this.EditPlayerAccountระบบไดรบขอมลPlayerAccountทมการแกไขระบบทำการตรวจสอบขอมลมการกรอกขอมลไมถกตองระบบไมสามารถสงขอมลไปทำการแกไขบญชผใชได("Nit", "Primary", "Visa", "5585067151394716", "3456", "12/31/2011");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[EditPlayerAccount]ระบบได้รับข้อมูล PlayerAccount ที่มีการแก้ไข ระบบทำการตรวจสอบข" +
            "้อมูล มีการกรอกข้อมูลไม่ถูกต้อง ระบบไม่สามารถส่งข้อมูลไปทำการแก้ไขบัญชีผู้ใช้ได้" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EditplayerAccount")]
        public virtual void EditPlayerAccountระบบไดรบขอมลPlayerAccountทมการแกไขระบบทำการตรวจสอบขอมลมการกรอกขอมลไมถกตองระบบไมสามารถสงขอมลไปทำการแกไขบญชผใชได_Variant7()
        {
            this.EditPlayerAccountระบบไดรบขอมลPlayerAccountทมการแกไขระบบทำการตรวจสอบขอมลมการกรอกขอมลไมถกตองระบบไมสามารถสงขอมลไปทำการแกไขบญชผใชได("Nit", "Primary", "Visa", "0012214544542345", "3456", "12/31/2011");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[EditPlayerAccount]ระบบได้รับข้อมูล PlayerAccount ที่มีการแก้ไข ระบบทำการตรวจสอบข" +
            "้อมูล มีการกรอกข้อมูลถูกต้อง ระบบสามารถส่งข้อมูลไปทำการแก้ไขบัญชีผู้ใช้ได้")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "EditplayerAccount")]
        public virtual void EditPlayerAccountระบบไดรบขอมลPlayerAccountทมการแกไขระบบทำการตรวจสอบขอมลมการกรอกขอมลถกตองระบบสามารถสงขอมลไปทำการแกไขบญชผใชได()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[EditPlayerAccount]ระบบได้รับข้อมูล PlayerAccount ที่มีการแก้ไข ระบบทำการตรวจสอบข" +
                    "้อมูล มีการกรอกข้อมูลถูกต้อง ระบบสามารถส่งข้อมูลไปทำการแก้ไขบัญชีผู้ใช้ได้", new string[] {
                        "record_mock"});
#line 25
this.ScenarioSetup(scenarioInfo);
#line 26
testRunner.Given("The EditPlayerAccountExecutor has been created and initialized");
#line 27
testRunner.And("Sent UserName \'Nit\' AccountType\'Primary\' CardType\'MasterCard\' AccountNo\'558506715" +
                    "1394716\' CVV\'1234\' ExpireDate\'12/31/2010\'");
#line 28
testRunner.When("Call EditPlayerAccountExecutor()");
#line 29
testRunner.Then("System can sent credit card information to sent player account to back server");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
