// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.5.2
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace TheS.Casinova.ChipExchange.WebExecutors.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.5.2")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class PayVoucherFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PayVoucherFeature.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "PayVoucher", "In order to pay voucher\r\nAs a system\r\nI want to pay voucher by bonus chips or chi" +
                    "ps", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            this.FeatureBackground();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "UserName",
                        "Password",
                        "Email",
                        "CellPhone",
                        "Upline",
                        "Refundable",
                        "NonRefundable",
                        "Active"});
            table1.AddRow(new string[] {
                        "OhAe",
                        "1234",
                        "sirinarin@hotmail.com",
                        "0892165437",
                        "Nit",
                        "500",
                        "200",
                        "True"});
            table1.AddRow(new string[] {
                        "Boy",
                        "5843",
                        "pongsak@gmail.com",
                        "0862202260",
                        "Nit",
                        "4500",
                        "500",
                        "True"});
            table1.AddRow(new string[] {
                        "Nit",
                        "1311",
                        "nayit_nit@hotmail.com",
                        "0892131356",
                        "",
                        "300",
                        "589",
                        "True"});
#line 8
testRunner.Given("Server has user profile information for pay voucher:", ((string)(null)), table1);
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบได้รับข้อมูล userName และ amount ครบ ระบบตรวจสอบจำนวนชิพทั้งหมดมีเพียงพอ ระบบ" +
            "สามารถส่งข้อมูลไป back server ได้")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PayVoucher")]
        public virtual void ระบบไดรบขอมลUserNameและAmountครบระบบตรวจสอบจำนวนชพทงหมดมเพยงพอระบบสามารถสงขอมลไปBackServerได()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ระบบได้รับข้อมูล userName และ amount ครบ ระบบตรวจสอบจำนวนชิพทั้งหมดมีเพียงพอ ระบบ" +
                    "สามารถส่งข้อมูลไป back server ได้", new string[] {
                        "record_mock",
                        "record_mock"});
#line 15
this.ScenarioSetup(scenarioInfo);
#line 16
testRunner.Given("The PayVoucherExecutor has been created and initialized");
#line 17
testRunner.And("Sent UserName\'Nit\' the player\'s profile should recieved");
#line 18
testRunner.And("Expected executed PayVoucherCommand");
#line 19
testRunner.When("Call PaVoucherExecutor(UserName\'Nit\', Amount\'500\')");
#line 20
testRunner.Then("The system can sent information to back server #PayVoucher");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบได้รับข้อมูล userName และ amount ครบ ระบบตรวจสอบจำนวนชิพทั้งหมดมีไม่เพียงพอ ร" +
            "ะบบไม่สามารถส่งข้อมูลไป back server ได้")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PayVoucher")]
        public virtual void ระบบไดรบขอมลUserNameและAmountครบระบบตรวจสอบจำนวนชพทงหมดมไมเพยงพอระบบไมสามารถสงขอมลไปBackServerได()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ระบบได้รับข้อมูล userName และ amount ครบ ระบบตรวจสอบจำนวนชิพทั้งหมดมีไม่เพียงพอ ร" +
                    "ะบบไม่สามารถส่งข้อมูลไป back server ได้", new string[] {
                        "record_mock"});
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
testRunner.Given("The PayVoucherExecutor has been created and initialized");
#line 25
testRunner.And("Sent UserName\'Nit\' the player\'s profile should recieved");
#line 26
testRunner.When("Call PaVoucherExecutor(UserName\'Nit\', Amount\'1000\')");
#line 27
testRunner.Then("The system can\'t sent information to back server #PayVoucher");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบได้รับข้อมูล userName และ amount ครบ แต่ไม่มี userName ใน server ระบบไม่สามาร" +
            "ถตรวจสอบจำนวนชิพทั้งหมดได้")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PayVoucher")]
        public virtual void ระบบไดรบขอมลUserNameและAmountครบแตไมมUserNameในServerระบบไมสามารถตรวจสอบจำนวนชพทงหมดได()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ระบบได้รับข้อมูล userName และ amount ครบ แต่ไม่มี userName ใน server ระบบไม่สามาร" +
                    "ถตรวจสอบจำนวนชิพทั้งหมดได้", new string[] {
                        "record_mock"});
#line 31
this.ScenarioSetup(scenarioInfo);
#line 32
testRunner.Given("The PayVoucherExecutor has been created and initialized");
#line 33
testRunner.And("Sent UserName\'Noy\' the player\'s profile should recieved null");
#line 34
testRunner.When("Call PaVoucherExecutor(UserName\'Noy\', Amount\'1000\')");
#line 35
testRunner.Then("The system can\'t sent information to back server #PayVoucher");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบไม่ได้รับข้อมูล userName ระบบไม่สามารถตรวจสอบจำนวนชิพทั้งหมดได้")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PayVoucher")]
        public virtual void ระบบไมไดรบขอมลUserNameระบบไมสามารถตรวจสอบจำนวนชพทงหมดได()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ระบบไม่ได้รับข้อมูล userName ระบบไม่สามารถตรวจสอบจำนวนชิพทั้งหมดได้", new string[] {
                        "record_mock"});
#line 38
this.ScenarioSetup(scenarioInfo);
#line 39
testRunner.Given("The PayVoucherExecutor has been created and initialized");
#line 40
testRunner.When("Call PaVoucherExecutor(UserName\'\', Amount\'1000\')");
#line 41
testRunner.Then("The system can\'t sent information to back server #PayVoucher");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบได้รับข้อมูล amount ไม่ถูกต้อง ระบบไม่สามารถตรวจสอบจำนวนชิพทั้งหมดได้")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PayVoucher")]
        public virtual void ระบบไดรบขอมลAmountไมถกตองระบบไมสามารถตรวจสอบจำนวนชพทงหมดได()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ระบบได้รับข้อมูล amount ไม่ถูกต้อง ระบบไม่สามารถตรวจสอบจำนวนชิพทั้งหมดได้", new string[] {
                        "record_mock"});
#line 44
this.ScenarioSetup(scenarioInfo);
#line 45
testRunner.Given("The PayVoucherExecutor has been created and initialized");
#line 46
testRunner.When("Call PaVoucherExecutor(UserName\'Nit\', Amount\'-1000\')");
#line 47
testRunner.Then("The system can\'t sent information to back server #PayVoucher");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
