// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.5.2
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace TheS.Casinova.ChipExchange.WebExecutors.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.5.2")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class VoucherToBonusChipsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "VoucherToBonusChipsFeature.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "VoucherToBonusChips", "In order to voucher to BonusChips exchange\r\nAs a system\r\nI want to sent voucher c" +
                    "ode to back server", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            this.FeatureBackground();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "UserName",
                        "VoucherCode",
                        "Amount",
                        "CanUse"});
            table1.AddRow(new string[] {
                        "Nit",
                        "0A15D",
                        "100",
                        "True"});
            table1.AddRow(new string[] {
                        "Ae",
                        "16F67",
                        "200",
                        "false"});
#line 8
testRunner.Given("Server has voucher information as :", ((string)(null)), table1);
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบได้รับข้อมูล voucher code และ userName ครบ  ระบบตรวจสอบการใช้งาน คูปองสามารถใ" +
            "ช้งานได้ ระบบส่งข้อมูลไป back server ได้")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "VoucherToBonusChips")]
        public virtual void ระบบไดรบขอมลVoucherCodeและUserNameครบระบบตรวจสอบการใชงานคปองสามารถใชงานไดระบบสงขอมลไปBackServerได()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ระบบได้รับข้อมูล voucher code และ userName ครบ  ระบบตรวจสอบการใช้งาน คูปองสามารถใ" +
                    "ช้งานได้ ระบบส่งข้อมูลไป back server ได้", new string[] {
                        "record_mock",
                        "record_mock"});
#line 14
this.ScenarioSetup(scenarioInfo);
#line 15
testRunner.Given("The VoucherToBonusChipsExecutor has been created and initialized");
#line 16
testRunner.And("Sent UserName\'Nit\' VoucherCode \'0A15D2C519764BF4B698E31B9F77FE90\' the player\'s vo" +
                    "ucher information should recieve");
#line 17
testRunner.When("Call VoucherToBonusChipsExecutor (UserName\'Nit\' VoucherCode \'0A15D2C519764BF4B698" +
                    "E31B9F77FE90\')");
#line 18
testRunner.Then("The system can sent information to back server #VoucherToBonusChips");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบได้รับข้อมูล voucher code และ userName ครบ  ระบบตรวจสอบการใช้งาน คูปองไม่สามา" +
            "รถใช้งานได้ ระบบส่งข้อมูลไป back server ไม่ได้")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "VoucherToBonusChips")]
        public virtual void ระบบไดรบขอมลVoucherCodeและUserNameครบระบบตรวจสอบการใชงานคปองไมสามารถใชงานไดระบบสงขอมลไปBackServerไมได()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ระบบได้รับข้อมูล voucher code และ userName ครบ  ระบบตรวจสอบการใช้งาน คูปองไม่สามา" +
                    "รถใช้งานได้ ระบบส่งข้อมูลไป back server ไม่ได้", new string[] {
                        "record_mock"});
#line 21
this.ScenarioSetup(scenarioInfo);
#line 22
testRunner.Given("The VoucherToBonusChipsExecutor has been created and initialized");
#line 23
testRunner.And("Sent UserName\'Ae\' VoucherCode \'16F67B16ABDF469FA42D6D3BFC380745\' the player\'s vou" +
                    "cher information should recieve");
#line 24
testRunner.When("Call VoucherToBonusChipsExecutor (UserName\'Ae\' VoucherCode \'16F67B16ABDF469FA42D6" +
                    "D3BFC380745\')");
#line 25
testRunner.Then("The system can\'t sent information to back server #VoucherToBonusChips");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบได้รับข้อมูล voucher code และ userName ครบ  ระบบตรวจสอบรหัสคูปอง ไม่มีข้อมูลค" +
            "ูปอง ระบบส่งข้อมูลไป back server ไม่ได้")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "VoucherToBonusChips")]
        public virtual void ระบบไดรบขอมลVoucherCodeและUserNameครบระบบตรวจสอบรหสคปองไมมขอมลคปองระบบสงขอมลไปBackServerไมได()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ระบบได้รับข้อมูล voucher code และ userName ครบ  ระบบตรวจสอบรหัสคูปอง ไม่มีข้อมูลค" +
                    "ูปอง ระบบส่งข้อมูลไป back server ไม่ได้", new string[] {
                        "record_mock"});
#line 28
this.ScenarioSetup(scenarioInfo);
#line 29
testRunner.Given("The VoucherToBonusChipsExecutor has been created and initialized");
#line 30
testRunner.And("Sent UserName\'Ae\' VoucherCode \'DA60FEA34A9D42299B8C066EDC141DC5\' the player\'s vou" +
                    "cher information should not recieve");
#line 31
testRunner.When("Call VoucherToBonusChipsExecutor (UserName\'Ae\' VoucherCode \'DA60FEA34A9D42299B8C0" +
                    "66EDC141DC5\')");
#line 32
testRunner.Then("The system can\'t sent information to back server #VoucherToBonusChips");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบไม่ได้รับข้อมูล voucher code ระบบส่งข้อมูลไป back server ไม่ได้_VoucherToBonu" +
            "sChips")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "VoucherToBonusChips")]
        public virtual void ระบบไมไดรบขอมลVoucherCodeระบบสงขอมลไปBackServerไมได_VoucherToBonusChips()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ระบบไม่ได้รับข้อมูล voucher code ระบบส่งข้อมูลไป back server ไม่ได้_VoucherToBonu" +
                    "sChips", new string[] {
                        "record_mock"});
#line 35
this.ScenarioSetup(scenarioInfo);
#line 36
testRunner.Given("The VoucherToBonusChipsExecutor has been created and initialized");
#line 37
testRunner.When("Call VoucherToBonusChipsExecutor (UserName\'Ae\' VoucherCode \'\')");
#line 38
testRunner.Then("The system can\'t sent information to back server #VoucherToBonusChips");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบไม่ได้รับข้อมูล UserName ระบบส่งข้อมูลไป back server ไม่ได้_VoucherToBonusChi" +
            "ps")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "VoucherToBonusChips")]
        public virtual void ระบบไมไดรบขอมลUserNameระบบสงขอมลไปBackServerไมได_VoucherToBonusChips()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ระบบไม่ได้รับข้อมูล UserName ระบบส่งข้อมูลไป back server ไม่ได้_VoucherToBonusChi" +
                    "ps", new string[] {
                        "record_mock"});
#line 41
this.ScenarioSetup(scenarioInfo);
#line 42
testRunner.Given("The VoucherToBonusChipsExecutor has been created and initialized");
#line 43
testRunner.When("Call VoucherToBonusChipsExecutor (UserName\'\' VoucherCode \'16F67B16ABDF469FA42D6D3" +
                    "BFC380745\')");
#line 44
testRunner.Then("The system can\'t sent information to back server #VoucherToBonusChips");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
