// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.5.2
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace PerfEx.Demo.SimpleGame.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.5.2")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class GetGamePlayInformationForUserFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "GetGameInformationForUser.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Get GamePlayInformationForUser", "In order to avoid silly mistakes\r\nAs a user\r\nI want to be told the game informati" +
                    "on that a user has play and game is active", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Sent username that available in game")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Get GamePlayInformationForUser")]
        public virtual void SentUsernameThatAvailableInGame()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Sent username that available in game", new string[] {
                        "record_mock"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 9
testRunner.Given("The GameTableConfigurator has been created and initialized");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "TableID",
                        "RoundID",
                        "TotalBetAmountOfBlack",
                        "TotalBetAmountOfWhite",
                        "LastUpdate",
                        "TrackingID",
                        "OnGoingTrackingID",
                        "Winner"});
            table1.AddRow(new string[] {
                        "1",
                        "5",
                        "10",
                        "20",
                        "10:00",
                        "B21F8971-DBAB-400F-9D95-151BA24875C1",
                        "B21F8971-DBAB-400F-9D95-151BA24875C1",
                        "White"});
            table1.AddRow(new string[] {
                        "2",
                        "6",
                        "34",
                        "32",
                        "10:00",
                        "C6BF4092-836B-4069-B2DD-392F8452FA91",
                        "C6BF4092-836B-4069-B2DD-392F8452FA91",
                        "Black"});
            table1.AddRow(new string[] {
                        "3",
                        "7",
                        "143",
                        "352",
                        "10:00",
                        "496B30C2-8849-49A2-B27F-CD0F5796D912",
                        "496B30C2-8849-49A2-B27F-CD0F5796D912",
                        "White"});
            table1.AddRow(new string[] {
                        "1",
                        "8",
                        "135",
                        "77",
                        "10:00",
                        "783B1532-D962-4719-A483-44613A136785",
                        "783B1532-D962-4719-A483-44613A136785",
                        "Black"});
            table1.AddRow(new string[] {
                        "2",
                        "9",
                        "67",
                        "388",
                        "10:00",
                        "AE27B886-D6C4-467C-8FE3-336CB5A5DC69",
                        "AE27B886-D6C4-467C-8FE3-336CB5A5DC69",
                        "White"});
#line 10
testRunner.And("server have John\'s gameInformation as", ((string)(null)), table1);
#line 19
testRunner.When("Call GetGamePlayInformationForUser(\'John\')");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "TableID",
                        "RoundID",
                        "TotalBetAmountOfBlack",
                        "TotalBetAmountOfWhite",
                        "LastUpdate",
                        "TrackingID",
                        "OnGoingTrackingID",
                        "Winner"});
            table2.AddRow(new string[] {
                        "1",
                        "5",
                        "10",
                        "20",
                        "10:00",
                        "B21F8971-DBAB-400F-9D95-151BA24875C1",
                        "B21F8971-DBAB-400F-9D95-151BA24875C1",
                        "White"});
            table2.AddRow(new string[] {
                        "2",
                        "6",
                        "34",
                        "32",
                        "10:00",
                        "C6BF4092-836B-4069-B2DD-392F8452FA91",
                        "C6BF4092-836B-4069-B2DD-392F8452FA91",
                        "Black"});
            table2.AddRow(new string[] {
                        "3",
                        "7",
                        "143",
                        "352",
                        "10:00",
                        "496B30C2-8849-49A2-B27F-CD0F5796D912",
                        "496B30C2-8849-49A2-B27F-CD0F5796D912",
                        "White"});
            table2.AddRow(new string[] {
                        "1",
                        "8",
                        "135",
                        "77",
                        "10:00",
                        "783B1532-D962-4719-A483-44613A136785",
                        "783B1532-D962-4719-A483-44613A136785",
                        "Black"});
            table2.AddRow(new string[] {
                        "2",
                        "9",
                        "67",
                        "388",
                        "10:00",
                        "AE27B886-D6C4-467C-8FE3-336CB5A5DC69",
                        "AE27B886-D6C4-467C-8FE3-336CB5A5DC69",
                        "White"});
#line 20
testRunner.Then("the result should be", ((string)(null)), table2);
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("username not available")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Get GamePlayInformationForUser")]
        public virtual void UsernameNotAvailable()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("username not available", new string[] {
                        "record_mock"});
#line 29
this.ScenarioSetup(scenarioInfo);
#line 31
testRunner.Given("The GameTableConfigurator has been created and initialized");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "TableID",
                        "RoundID",
                        "TotalBetAmountOfBlack",
                        "TotalBetAmountOfWhite",
                        "LastUpdate",
                        "TrackingID",
                        "OnGoingTrackingID",
                        "Winner"});
            table3.AddRow(new string[] {
                        "1",
                        "5",
                        "10",
                        "20",
                        "10:00",
                        "B21F8971-DBAB-400F-9D95-151BA24875C1",
                        "B21F8971-DBAB-400F-9D95-151BA24875C1",
                        "White"});
            table3.AddRow(new string[] {
                        "2",
                        "6",
                        "34",
                        "32",
                        "10:00",
                        "C6BF4092-836B-4069-B2DD-392F8452FA91",
                        "C6BF4092-836B-4069-B2DD-392F8452FA91",
                        "Black"});
            table3.AddRow(new string[] {
                        "3",
                        "7",
                        "143",
                        "352",
                        "10:00",
                        "496B30C2-8849-49A2-B27F-CD0F5796D912",
                        "496B30C2-8849-49A2-B27F-CD0F5796D912",
                        "White"});
            table3.AddRow(new string[] {
                        "1",
                        "8",
                        "135",
                        "77",
                        "10:00",
                        "783B1532-D962-4719-A483-44613A136785",
                        "783B1532-D962-4719-A483-44613A136785",
                        "Black"});
            table3.AddRow(new string[] {
                        "2",
                        "9",
                        "67",
                        "388",
                        "10:00",
                        "AE27B886-D6C4-467C-8FE3-336CB5A5DC69",
                        "AE27B886-D6C4-467C-8FE3-336CB5A5DC69",
                        "White"});
#line 32
testRunner.And("server have Yui\'s gameInformation as", ((string)(null)), table3);
#line 41
testRunner.When("Call GetGamePlayInformationForUser(\'Yui\')");
#line 42
testRunner.Then("the result should be empty");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
