// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.5.2
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace TheS.Casinova.Colors.WebExecutors.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.5.2")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class CheckActiveRoundToCreateFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CheckActiveRoundFeature.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CheckActiveRoundToCreate", "In order to check active round\r\nAs a system\r\nI want to check active round for sen" +
                    "t command to back server", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบส่งค่า Name ถูกต้อง ระบบตรวจสอบจำนวน active round ที่มี มีค่าเท่ากับจำนวน act" +
            "ive round ทั้งหมดที่ระบบต้องการ")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CheckActiveRoundToCreate")]
        public virtual void ระบบสงคาNameถกตองระบบตรวจสอบจำนวนActiveRoundทมมคาเทากบจำนวนActiveRoundทงหมดทระบบตองการ()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ระบบส่งค่า Name ถูกต้อง ระบบตรวจสอบจำนวน active round ที่มี มีค่าเท่ากับจำนวน act" +
                    "ive round ทั้งหมดที่ระบบต้องการ", new string[] {
                        "record_mock"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
testRunner.Given("The GameRoundConfigurations has been created and initialized");
#line 9
testRunner.And("Active round has\'5\', Expect active round \'5\'");
#line 10
testRunner.When("Execute CheckActiveRoundToCreateCommand");
#line 11
testRunner.Then("The system don\'t add ActiveRound");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบตรวจสอบจำนวน active round ที่มี มีค่ามากกว่าจำนวน active round ทั้งหมดที่ระบบ" +
            "ต้องการ")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CheckActiveRoundToCreate")]
        public virtual void ระบบตรวจสอบจำนวนActiveRoundทมมคามากกวาจำนวนActiveRoundทงหมดทระบบตองการ()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ระบบตรวจสอบจำนวน active round ที่มี มีค่ามากกว่าจำนวน active round ทั้งหมดที่ระบบ" +
                    "ต้องการ", new string[] {
                        "record_mock"});
#line 14
this.ScenarioSetup(scenarioInfo);
#line 15
testRunner.Given("The GameRoundConfigurations has been created and initialized");
#line 16
testRunner.And("Active round has\'6\', Expect active round \'5\'");
#line 17
testRunner.When("Execute CheckActiveRoundToCreateCommand");
#line 18
testRunner.Then("The system don\'t add ActiveRound");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบตรวจสอบจำนวน active round ที่มี มีค่าน้อยกว่าจำนวน active round ทั้งหมดที่ระบ" +
            "บต้องการ")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CheckActiveRoundToCreate")]
        public virtual void ระบบตรวจสอบจำนวนActiveRoundทมมคานอยกวาจำนวนActiveRoundทงหมดทระบบตองการ()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ระบบตรวจสอบจำนวน active round ที่มี มีค่าน้อยกว่าจำนวน active round ทั้งหมดที่ระบ" +
                    "บต้องการ", new string[] {
                        "record_mock"});
#line 21
this.ScenarioSetup(scenarioInfo);
#line 22
testRunner.Given("The GameRoundConfigurations has been created and initialized");
#line 23
testRunner.And("Active round has\'4\', Expect active round \'5\'");
#line 24
testRunner.When("Execute CheckActiveRoundToCreateCommand");
#line 25
testRunner.Then("The system sent command to back server");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบไม่ได้ส่งค่า Name ระบบไม่สามารถตรวจสอบจำนวน active round ได้")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "CheckActiveRoundToCreate")]
        public virtual void ระบบไมไดสงคาNameระบบไมสามารถตรวจสอบจำนวนActiveRoundได()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ระบบไม่ได้ส่งค่า Name ระบบไม่สามารถตรวจสอบจำนวน active round ได้", new string[] {
                        "record_mock"});
#line 28
this.ScenarioSetup(scenarioInfo);
#line 29
testRunner.Given("The GameRoundConfigurations has been created and initialized");
#line 30
testRunner.When("Execute CheckActiveRoundToCreateCommand");
#line 31
testRunner.Then("The system don\'t add ActiveRound");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
