// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.5.2
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace TheS.Casinova.Colors.WebExecutors.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.5.2")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ListGamePlayInfoFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ListGamePlayInfoFeature.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ListGamePlayInfo", "In order to list game play information\r\nAs a system\r\nI want to list game play inf" +
                    "ormation of player", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            this.FeatureBackground();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "UserProfileBalance",
                        "GameRoundInfoRoundID",
                        "TotalBetAmountOfBlack",
                        "TotalBetAmountOfWhite",
                        "Winner",
                        "LastUpdate",
                        "TrackingID",
                        "OnGoingTrackingID",
                        "UserProfileBalance"});
            table1.AddRow(new string[] {
                        "Lala",
                        "5",
                        "320",
                        "20",
                        "Black",
                        "10:00",
                        "{BAF9F79B-BDCC-4FA5-804D-9C8B4ED42887}",
                        "{BAF9F79B-BDCC-4FA5-804D-9C8B4ED42887}",
                        "Lala"});
            table1.AddRow(new string[] {
                        "Lala",
                        "6",
                        "40",
                        "30",
                        "White",
                        "12:00",
                        "{046CDB68-8B43-431C-8584-11A6049C0CF4}",
                        "{046CDB68-8B43-431C-8584-11A6049C0CF4}",
                        "Lala"});
            table1.AddRow(new string[] {
                        "Lala",
                        "7",
                        "11",
                        "100",
                        "White",
                        "15:00",
                        "{046CDB68-8B43-431C-8584-11A6049C0CF4}",
                        "{F0A52B67-DC51-424F-BF2E-CA72D8E07FA8}",
                        "Lala"});
#line 8
testRunner.Given("Server has game play information as:", ((string)(null)), table1);
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบลิสต์ข้อมูลโต๊ะเกมที่ผู้เล่นเคยเล่นไว้ได้")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ListGamePlayInfo")]
        public virtual void ระบบลสตขอมลโตะเกมทผเลนเคยเลนไวได()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ระบบลิสต์ข้อมูลโต๊ะเกมที่ผู้เล่นเคยเล่นไว้ได้", new string[] {
                        "record_mock"});
#line 15
this.ScenarioSetup(scenarioInfo);
#line 16
testRunner.Given("The ListGamePlayInfoExecutor has been created and initialized");
#line 17
testRunner.When("Call ListGamePlayInfoExecutor(\'Lala\')");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "UserProfileBalance",
                        "GameRoundInfoRoundID",
                        "TotalBetAmountOfBlack",
                        "TotalBetAmountOfWhite",
                        "Winner",
                        "LastUpdate",
                        "TrackingID",
                        "OnGoingTrackingID",
                        "UserProfileBalance"});
            table2.AddRow(new string[] {
                        "Lala",
                        "5",
                        "320",
                        "20",
                        "Black",
                        "10:00",
                        "{BAF9F79B-BDCC-4FA5-804D-9C8B4ED42887}",
                        "{BAF9F79B-BDCC-4FA5-804D-9C8B4ED42887}",
                        "Lala"});
            table2.AddRow(new string[] {
                        "Lala",
                        "6",
                        "40",
                        "30",
                        "White",
                        "12:00",
                        "{046CDB68-8B43-431C-8584-11A6049C0CF4}",
                        "{046CDB68-8B43-431C-8584-11A6049C0CF4}",
                        "Lala"});
            table2.AddRow(new string[] {
                        "Lala",
                        "7",
                        "11",
                        "100",
                        "White",
                        "15:00",
                        "{046CDB68-8B43-431C-8584-11A6049C0CF4}",
                        "{F0A52B67-DC51-424F-BF2E-CA72D8E07FA8}",
                        "Lala"});
#line 18
testRunner.Then("The game play information should be :", ((string)(null)), table2);
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบลิสต์ข้อมูลโต๊ะเกมแต่ไม่มีข้อมูล เนื่องจากผู้เล่นยังไม่เคยเล่นเกมที่โต๊ะใด ๆ")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ListGamePlayInfo")]
        public virtual void ระบบลสตขอมลโตะเกมแตไมมขอมลเนองจากผเลนยงไมเคยเลนเกมทโตะใดๆ()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ระบบลิสต์ข้อมูลโต๊ะเกมแต่ไม่มีข้อมูล เนื่องจากผู้เล่นยังไม่เคยเล่นเกมที่โต๊ะใด ๆ", new string[] {
                        "record_mock"});
#line 25
this.ScenarioSetup(scenarioInfo);
#line 26
testRunner.Given("The ListGamePlayInfoExecutor has been created and initialized");
#line 27
testRunner.When("Call ListGamePlayInfoExecutor(\'Nit\')");
#line 28
testRunner.Then("The game play information should be null");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบไม่ได้รับข้อมูล username ระบบลิสต์ข้อมูลโต๊ะเกมไม่ได้")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ListGamePlayInfo")]
        public virtual void ระบบไมไดรบขอมลUsernameระบบลสตขอมลโตะเกมไมได()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ระบบไม่ได้รับข้อมูล username ระบบลิสต์ข้อมูลโต๊ะเกมไม่ได้", new string[] {
                        "record_mock"});
#line 31
this.ScenarioSetup(scenarioInfo);
#line 32
testRunner.Given("The ListGamePlayInfoExecutor has been created and initialized");
#line 33
testRunner.When("Call ListGamePlayInfoExecutor(\'\')");
#line 34
testRunner.Then("The game play information should be throw exception");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ใส่ข้อมูล username ที่ไม่มีในระบบ ระบบทำการลิสต์ข้อมูล ไม่มีข้อมูลโต๊ะเกม")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ListGamePlayInfo")]
        public virtual void ใสขอมลUsernameทไมมในระบบระบบทำการลสตขอมลไมมขอมลโตะเกม()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ใส่ข้อมูล username ที่ไม่มีในระบบ ระบบทำการลิสต์ข้อมูล ไม่มีข้อมูลโต๊ะเกม", new string[] {
                        "record_mock"});
#line 37
this.ScenarioSetup(scenarioInfo);
#line 38
testRunner.Given("The ListGamePlayInfoExecutor has been created and initialized");
#line 39
testRunner.When("Call ListGamePlayInfoExecutor(\'Boy\')");
#line 40
testRunner.Then("The game play information should be null");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
