// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.5.2
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace TheS.Casinova.TwoWins.WebExecutors.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.5.2")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ListbetLogInfoFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ListBetLogInfoFeature.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ListbetLogInfo", "In order to list bet log information\r\nAs a system\r\nI want to list bet log informa" +
                    "tion", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            this.FeatureBackground();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "RoundID",
                        "UserName",
                        "HandID",
                        "Amount",
                        "HandStatus",
                        "BetDateTime"});
            table1.AddRow(new string[] {
                        "1",
                        "Nayit",
                        "1",
                        "700",
                        "Normal",
                        "10:54 12/13/2010"});
            table1.AddRow(new string[] {
                        "2",
                        "Nayit",
                        "1",
                        "28",
                        "Normal",
                        "10:58 12/13/2010"});
            table1.AddRow(new string[] {
                        "1",
                        "Nayit",
                        "2",
                        "1500",
                        "Normal",
                        "11:02 12/13/2010"});
            table1.AddRow(new string[] {
                        "1",
                        "Kob",
                        "3",
                        "44",
                        "Normal",
                        "11:14 12/13/2010"});
            table1.AddRow(new string[] {
                        "2",
                        "Eye",
                        "2",
                        "550",
                        "Normal",
                        "11:20 12/13/2010"});
            table1.AddRow(new string[] {
                        "1",
                        "Krai",
                        "4",
                        "133",
                        "Normal",
                        "11:21 12/13/2010"});
            table1.AddRow(new string[] {
                        "2",
                        "Jae",
                        "3",
                        "1000",
                        "Critical",
                        "11:29 12/13/2010"});
            table1.AddRow(new string[] {
                        "1",
                        "Sak",
                        "5",
                        "323",
                        "Critical",
                        "11:30 12/13/2010"});
#line 8
testRunner.Given("Server has bet log information as :", ((string)(null)), table1);
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[ListBetLogInfo] ระบบได้รับข้อมูล UserName, RoundID ถูกต้อง ระบบสามารถดึงข้อมูล B" +
            "etLogInformation ได้")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ListbetLogInfo")]
        public virtual void ListBetLogInfoระบบไดรบขอมลUserNameRoundIDถกตองระบบสามารถดงขอมลBetLogInformationได()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[ListBetLogInfo] ระบบได้รับข้อมูล UserName, RoundID ถูกต้อง ระบบสามารถดึงข้อมูล B" +
                    "etLogInformation ได้", new string[] {
                        "record_mock",
                        "record_mock"});
#line 21
this.ScenarioSetup(scenarioInfo);
#line 22
testRunner.Given("The ListBetLogInfoExecutor has been created and initialized");
#line 23
testRunner.And("Sent UserName\'Nayit\' RoundID\'1\' to list bet log information");
#line 24
testRunner.When("Call ListBetLogInfoExecutor()");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "RoundID",
                        "UserName",
                        "HandID",
                        "Amount",
                        "HandStatus",
                        "BetDateTime"});
            table2.AddRow(new string[] {
                        "1",
                        "Nayit",
                        "1",
                        "700",
                        "Normal",
                        "10:54 12/13/2010"});
            table2.AddRow(new string[] {
                        "1",
                        "Nayit",
                        "2",
                        "1500",
                        "Normal",
                        "11:02 12/13/2010"});
#line 25
testRunner.Then("BetLog information should be as :", ((string)(null)), table2);
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[ListBetLogInfo] ระบบได้รับข้อมูล RoundID ที่ยังไม่มีข้อมูลใน database ได้ข้อมูล " +
            "BetLogInformation เป็น null")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ListbetLogInfo")]
        public virtual void ListBetLogInfoระบบไดรบขอมลRoundIDทยงไมมขอมลในDatabaseไดขอมลBetLogInformationเปนNull()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[ListBetLogInfo] ระบบได้รับข้อมูล RoundID ที่ยังไม่มีข้อมูลใน database ได้ข้อมูล " +
                    "BetLogInformation เป็น null", new string[] {
                        "record_mock"});
#line 31
this.ScenarioSetup(scenarioInfo);
#line 32
testRunner.Given("The ListBetLogInfoExecutor has been created and initialized");
#line 33
testRunner.And("Sent UserName\'Nayit\' RoundID\'3\' to list bet log information");
#line 34
testRunner.When("Call ListBetLogInfoExecutor()");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "RoundID",
                        "UserName",
                        "HandID",
                        "Amount",
                        "HandStatus",
                        "BetDateTime"});
#line 35
testRunner.Then("BetLog information should be as :", ((string)(null)), table3);
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[ListBetLogInfo] ระบบได้รับข้อมูล UserName ที่ยังไม่มีข้อมูลใน database ได้ข้อมูล" +
            " BetLogInformation เป็น null")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ListbetLogInfo")]
        public virtual void ListBetLogInfoระบบไดรบขอมลUserNameทยงไมมขอมลในDatabaseไดขอมลBetLogInformationเปนNull()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[ListBetLogInfo] ระบบได้รับข้อมูล UserName ที่ยังไม่มีข้อมูลใน database ได้ข้อมูล" +
                    " BetLogInformation เป็น null", new string[] {
                        "record_mock"});
#line 39
this.ScenarioSetup(scenarioInfo);
#line 40
testRunner.Given("The ListBetLogInfoExecutor has been created and initialized");
#line 41
testRunner.And("Sent UserName\'Pla\' RoundID\'1\' to list bet log information");
#line 42
testRunner.When("Call ListBetLogInfoExecutor()");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "RoundID",
                        "UserName",
                        "HandID",
                        "Amount",
                        "HandStatus",
                        "BetDateTime"});
#line 43
testRunner.Then("BetLog information should be as :", ((string)(null)), table4);
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[ListBetLogInfo] ระบบได้รับข้อมูล UserName ไม่ถูกต้อง ระบบไม่สามารถดึงข้อมูล BetL" +
            "ogInformation ได้")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ListbetLogInfo")]
        public virtual void ListBetLogInfoระบบไดรบขอมลUserNameไมถกตองระบบไมสามารถดงขอมลBetLogInformationได()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[ListBetLogInfo] ระบบได้รับข้อมูล UserName ไม่ถูกต้อง ระบบไม่สามารถดึงข้อมูล BetL" +
                    "ogInformation ได้", new string[] {
                        "record_mock"});
#line 47
this.ScenarioSetup(scenarioInfo);
#line 48
testRunner.Given("The ListBetLogInfoExecutor has been created and initialized");
#line 49
testRunner.And("Sent UserName\'\' RoundID\'1\' for list bet log information validation");
#line 50
testRunner.When("Call ListBetLogInfoExecutor() for validate input");
#line 51
testRunner.Then("BetLog information should be throw exception");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[ListBetLogInfo] ระบบได้รับข้อมูล RoundID ไม่ถูกต้อง ระบบไม่สามารถดึงข้อมูล BetLo" +
            "gInformation ได้")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ListbetLogInfo")]
        public virtual void ListBetLogInfoระบบไดรบขอมลRoundIDไมถกตองระบบไมสามารถดงขอมลBetLogInformationได()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[ListBetLogInfo] ระบบได้รับข้อมูล RoundID ไม่ถูกต้อง ระบบไม่สามารถดึงข้อมูล BetLo" +
                    "gInformation ได้", new string[] {
                        "record_mock"});
#line 54
this.ScenarioSetup(scenarioInfo);
#line 55
testRunner.Given("The ListBetLogInfoExecutor has been created and initialized");
#line 56
testRunner.And("Sent UserName\'Nayit\' RoundID\'-1\' for list bet log information validation");
#line 57
testRunner.When("Call ListBetLogInfoExecutor() for validate input");
#line 58
testRunner.Then("BetLog information should be throw exception");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
