// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.5.2
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace TheS.Casinova.TwoWins.WebExecutors.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.5.2")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class SingleBetFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SingleBetFeature.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SingleBet", "In order to single bet\r\nAs a system\r\nI want to sent single bet information to bac" +
                    "k server", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[SingleBet]ระบบได้รับข้อมูล SingleBet ถูกต้อง ระบบสามารถ generate trackingID และส" +
            "่งข้อมูลไปยัง back server ได้")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "SingleBet")]
        public virtual void SingleBetระบบไดรบขอมลSingleBetถกตองระบบสามารถGenerateTrackingIDและสงขอมลไปยงBackServerได()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[SingleBet]ระบบได้รับข้อมูล SingleBet ถูกต้อง ระบบสามารถ generate trackingID และส" +
                    "่งข้อมูลไปยัง back server ได้", new string[] {
                        "record_mock"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
testRunner.Given("The SingleBetExecutor has been created and initialized");
#line 9
testRunner.And("Sent UserName\'Nayit\' RoundID \'1\' Amount\'100\'");
#line 10
testRunner.And("TrackingID for SibgleBet is \'4A3D921113824255ABA59FCC6A4EC168\'");
#line 11
testRunner.When("Call SingleBetExecutor()");
#line 12
testRunner.Then("TrackingID for SingleBet should be :\'4A3D921113824255ABA59FCC6A4EC168\'");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SingleBetระบบไดรบขอมลSingleBetไมถกตองระบบไมสามารถGenerateTrackingIDและสงขอมลไปยงBackServerได(string userName, string roundID, string amount)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[SingleBet]ระบบได้รับข้อมูล SingleBet ไม่ถูกต้อง ระบบไม่สามารถ generate trackingI" +
                    "D และส่งข้อมูลไปยัง back server ได้", new string[] {
                        "record_mock"});
#line 15
this.ScenarioSetup(scenarioInfo);
#line 16
testRunner.Given("The SingleBetExecutor has been created and initialized");
#line 17
testRunner.And(string.Format("Sent UserName\'{0}\' RoundID \'{1}\' Amount\'{2}\' for single bet validation", userName, roundID, amount));
#line 18
testRunner.When("Call SingleBetExecutor() for validate input");
#line 19
testRunner.Then("SingleBet get null and skip checking trackingID");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[SingleBet]ระบบได้รับข้อมูล SingleBet ไม่ถูกต้อง ระบบไม่สามารถ generate trackingI" +
            "D และส่งข้อมูลไปยัง back server ได้")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "SingleBet")]
        public virtual void SingleBetระบบไดรบขอมลSingleBetไมถกตองระบบไมสามารถGenerateTrackingIDและสงขอมลไปยงBackServerได_Variant0()
        {
            this.SingleBetระบบไดรบขอมลSingleBetไมถกตองระบบไมสามารถGenerateTrackingIDและสงขอมลไปยงBackServerได("", "1", "200");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[SingleBet]ระบบได้รับข้อมูล SingleBet ไม่ถูกต้อง ระบบไม่สามารถ generate trackingI" +
            "D และส่งข้อมูลไปยัง back server ได้")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "SingleBet")]
        public virtual void SingleBetระบบไดรบขอมลSingleBetไมถกตองระบบไมสามารถGenerateTrackingIDและสงขอมลไปยงBackServerได_Variant1()
        {
            this.SingleBetระบบไดรบขอมลSingleBetไมถกตองระบบไมสามารถGenerateTrackingIDและสงขอมลไปยงBackServerได("Nayit", "-1", "89");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("[SingleBet]ระบบได้รับข้อมูล SingleBet ไม่ถูกต้อง ระบบไม่สามารถ generate trackingI" +
            "D และส่งข้อมูลไปยัง back server ได้")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "SingleBet")]
        public virtual void SingleBetระบบไดรบขอมลSingleBetไมถกตองระบบไมสามารถGenerateTrackingIDและสงขอมลไปยงBackServerได_Variant2()
        {
            this.SingleBetระบบไดรบขอมลSingleBetไมถกตองระบบไมสามารถGenerateTrackingIDและสงขอมลไปยงBackServerได("Nayit", "2", "0");
        }
    }
}
#endregion
