// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.5.2
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace TheS.Casinova.ColorsGame.WebExecutors.Specs.Steps
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.5.2")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class GenerateTrackingIDForClientAndBackServiceFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "GenerateTrackingID.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Generate TrackingID For Client and BackService", "In order to generate TrackingID\r\nAs a WebServer\r\nI want to request winner for the" +
                    " WebServer ganarate TrackingID", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ระบบสงคาขอมลTableIDและRoundID(string tableId, string roundId)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ระบบส่งค่าข้อมูล tableID และ roundID", new string[] {
                        "record_mock"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
testRunner.Given("The PayForWinnerInfoExecutor  has been created and initialized");
#line 9
testRunner.And(string.Format("Request winner from TableID \'{0}\', RoundID \'{1}\' UserName \'nit\'", tableId, roundId));
#line 10
testRunner.And("Expect call IColorGameBackService.PayForWinnerInfo()");
#line 11
testRunner.When(string.Format("Execute PayForColorsWinnerInfoCommand(TableID \'{0}\', RoundID \'{1}\') by UserName \'" +
                        "nit\'", tableId, roundId));
#line 12
testRunner.Then("The result should be executeCommand by calling IColorGameBackService.PayForWinner" +
                    "Info()");
#line 13
testRunner.And("The WebServer can generated TrackingID");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบส่งค่าข้อมูล tableID และ roundID")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Generate TrackingID For Client and BackService")]
        public virtual void ระบบสงคาขอมลTableIDและRoundID_1()
        {
            this.ระบบสงคาขอมลTableIDและRoundID("1", "5");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบส่งค่าข้อมูล tableID และ roundID")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Generate TrackingID For Client and BackService")]
        public virtual void ระบบสงคาขอมลTableIDและRoundID_2()
        {
            this.ระบบสงคาขอมลTableIDและRoundID("2", "6");
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ระบบส่งค่าข้อมูล tableID และ roundID")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Generate TrackingID For Client and BackService")]
        public virtual void ระบบสงคาขอมลTableIDและRoundID_3()
        {
            this.ระบบสงคาขอมลTableIDและRoundID("3", "7");
        }
    }
}
#endregion
