// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.5.2
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace TheS.Casinova.PlayerProfile.BackServices.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.5.2")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ChangeEmailFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ChangeEmail.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ChangeEmail", "In order to change e-mail\r\nAs a back server\r\nI want to be update new e-mail", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            this.FeatureBackground();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "UserName",
                        "E-mail"});
            table1.AddRow(new string[] {
                        "OhAe",
                        "aaa@aaa.com"});
            table1.AddRow(new string[] {
                        "Boy",
                        "bbb@bbb.com"});
            table1.AddRow(new string[] {
                        "Nittaya",
                        "ccc@ccc.com"});
            table1.AddRow(new string[] {
                        "Au",
                        "ddd@ddd.com"});
#line 7
testRunner.Given("(ChangeEmail)server has user profile information as:", ((string)(null)), table1);
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("ได้รับข้อมูล E-mail ที่ต้องการเปลี่ยน, E-mail เก่าถูกต้องและ E-mail ใหม่ไม่ซ้ำกับ" +
            " E-mail ที่มีอยู่่ในระบบ, ระบบเปลี่ยนแปลงรหัส E-mail ของผู้เล่นในระบบ")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ChangeEmail")]
        public virtual void ไดรบขอมลE_MailทตองการเปลยนE_MailเกาถกตองและE_MailใหมไมซำกบE_MailทมอยในระบบระบบเปลยนแปลงรหสE_Mailของผเลนในระบบ()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ได้รับข้อมูล E-mail ที่ต้องการเปลี่ยน, E-mail เก่าถูกต้องและ E-mail ใหม่ไม่ซ้ำกับ" +
                    " E-mail ที่มีอยู่่ในระบบ, ระบบเปลี่ยนแปลงรหัส E-mail ของผู้เล่นในระบบ", new string[] {
                        "record_mock"});
#line 15
this.ScenarioSetup(scenarioInfo);
#line 16
testRunner.Given("The ChangeEmail has been created and initialized");
#line 17
testRunner.And("the old email should be correct(UserName: \'OhAe\', OldE-mail: \'aaa@aaa.com\')");
#line 18
testRunner.And("the new email should be unique(NewE-mail: \'a@a.com\')");
#line 19
testRunner.And("the user profile should be update(UserName: \'OhAe\', OldE-mail: \'aaa@aaa.com\', New" +
                    "E-mail: \'a@a.com\')");
#line 20
testRunner.When("call ChangeEmailExecutor(UserName: \'OhAe\', OldE-mail: \'aaa@aaa.com\', NewE-mail: \'" +
                    "a@a.com\')");
#line 21
testRunner.Then("the e-mail should be update in user profile");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
